### ISSUE TITLE
Question about GPU

### ISSUE THREAD

**Issue by 7sharp9** [jrdrg/reason-gameboy-emulator#1]
Hi I just wondered if you had any thought on how you would be using the GPU.  I like making emulators I have a few in different levels of completion, 6502C in F#/Fable and a 68000 in plain F#.  :-)

**Comment by jrdrg** [comment]
To be honest I haven't yet thought about it, this is the first emulator I've written and it's pretty far away from the point where I figure I should start thinking about optimization a bit more. Do you have any suggestions?

**Comment by 7sharp9** [comment]
Nope, no suggestions, Im just generally interested in this area! :-)
